# Earlier travis
# install:
#    - sudo apt-get -qq update
#    - sudo apt-get install libwxgtk3.0-dev libgps-dev libglu1-mesa-dev libgtk2.0-dev libbz2-dev libtinyxml-dev 
#    - sudo apt-get install libportaudio2 portaudio19-dev libcurl4-openssl-dev libexpat1-dev libcairo2-dev librtlsdr-dev
#    - sudo apt-get install rpm
#script:
#  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
#    then
#      echo "Don't build on coverty_scan branch.";
#      exit 0;
#    fi
#  - mkdir build && cd build
#  - cmake -DCMAKE_BUILD_TYPE=Release ../
#  - make -j2 package
#============

# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp

matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=osx
      os: osx
      compiler: clang
      script:
        - bash ./ci/travis-build-osx.sh

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
# Set encrypted variable 'GitHub_auth_token' in Travis repo settings to deploy packages
# for tagged commits to GitHub Releases.
deploy:
- provider: releases
  api_key:  #for weatherfax
   secure:"oMEBfnuulqTorg40G4VAKrMjToYQRhbejr/m7uJZqld/bE4fNFcUppEuAno8uQA9CXOSbrv6m+D4DJa0Za3K2ppDtcBNfxIuFq1Nxs97TMfQdFL3ywBXo2V119e6VWvHP05kMSJx8ECuqWlE8EhKIoHH9aKTnVmuPMqCrpd8Tkfn4KQSRrJ9WzgivEILgb3GSb8fI2GTgOwf4dN8F1lSDdIcw1VciPKyZj9OeSc+Tj87lcxwVjSPJyek9lnnpQ8HQXHzqq0pPD4R91veT+LKMrmnkit8z1fhDm/JY31HHf3F5YuWLfSYRotLfHR/KTwDiD0K0tJohZ5Cl4Dm+r1XMUxaPY9YBlWNqa8cSUPEAcy1bU/r+Dz6py+wVpyrEdYs0CNMUUM7X3hYeompsmRi/WvGl0GL9sTYEm8QHLETExIdxGJ/8E8o1LtzOBrTPkmV/xVMmFqzFlS1xwAKeSvtxbQZfjmIyNr1NOBhEYvmBfq2fs4iU63Kpb8XkylQdQ4TZ64w+jnBRZ5vAWunvM0WbbVzy8W3ykT9sx5eUqEcTfvNd8ghoGWnIX+7L6KXRYDiWyRtzvkhW7S0Dr5IfLAsrkdIYyN+6Ll5/6l5tVOlYePnEG560lBPBGrLBlMSIbaTnokYpTq1LwMexSYg3g0BbEulWi5VOcuyVB7o3JmVpNA="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,rpm,dmg,txz,pkg,pkg.tar.xz}"
  skip_cleanup: true
  on:  # Set deploy conditions
    repo: rgleason/weatherfax_pi
    tags: true    # Deploy only when tag is specified
    all_branches: true  # or this branch  branch: dev

